### ISSUE TITLE
ROThumbnailGenerator doesn't work for swift 2.3

### ISSUE THREAD

**Issue by mwleinad** [prine/ROThumbnailGenerator#4]
It will be nice if you can release a version for 2.3. 
it doesn't require a lot of changes (actually I think is just 2 lines of code)
but we would like to use that version instead of hardcoding the changes in our pods.

thanks!

**Comment by prine** [comment]
Yeah, I've already updated to Swift 3.0. You could use one of the old tags https://github.com/prine/ROThumbnailGenerator/releases/tag/2.0.1 there it should work with Swift 2.0 and I hope also Swift 2.3. If not feel free to fork this tag and update the lines to work with 2.3.

**Comment by prine** [comment]
I have created a new branch called swift-2.3 and a new release 1.0.4 which is now Swift 2.3 ready.
